### ISSUE TITLE
Website link `Page Not Found`

### ISSUE THREAD

**Issue by Wei-1** [virtuber/openvtuber#53]
The website link in the `About` in GitHub is not pointing to a correct URL.
I will suggest pointing to https://openvtuber.com/ directly

**Comment by seendsouza** [comment]
That's actually going to be a link to the client, but we haven't deployed it yet. I'll fix it today. Thanks for the feedback!

**Comment by hatkidchan** [comment]
Can it be reopened? Link is dead again and domain is apparently for sale

**Comment by seendsouza** [comment]
Yep will fix when I have time

**Comment by seendsouza** [comment]
Fixed
